---
- hosts: all
  sudo: true
  tasks:
    - name: Install binaries
      yum: name={{ item }} state=latest
      with_items:
        - vim
        - git
        - wget
        - gcc
        - make
        - automake
        - autoconf
        - libtool
        - pcre
        - pcre-devel
        - libxml2
        - libxml2-devel
        - curl
        - curl-devel
        - httpd-devel
        - openssl-devel
        - mlogc
    - name: Add nginx group
      group: name=nginx
    - name: Add nginx user
      user: name=nginx comment="Nginx web server" shell=/sbin/nologin home=/var/lib/nginx group=nginx
    - name: Set permissions of modsecurity log directory
      file: path=/var/log/mlogc/data owner=root group=nginx mode=0770
    - name: Clone modsecurity project
      git: repo=https://github.com/SpiderLabs/ModSecurity.git dest=/root/modsecurity update=no
    - name: Copy patch file
      copy: src=../patches/modsec.patch dest=/root/modsec.patch
    - name: Apply patch
      command: /usr/bin/patch -p2 -i /root/modsec.patch chdir=/root
    - name: Compile modsecurity step 1
      command: ./autogen.sh chdir=/root/modsecurity
    - name: Compile modsecurity step 2
      command: ./configure --enable-standalone-module chdir=/root/modsecurity
    - name: Compile modsecurity step 3
      command: make chdir=/root/modsecurity
    - name: Download nginx
      get_url: url=http://nginx.org/download/nginx-1.8.0.tar.gz dest=/tmp
    - name: Uncompress nginx
      command: /bin/tar -xzf /tmp/nginx-1.8.0.tar.gz --directory=/root
    - name: Compile nginx step 1
      command: ./configure --add-module=../modsecurity/nginx/modsecurity/ --user=nginx --group=nginx --with-pcre-jit --with-debug --with-ipv6 --with-http_ssl_module --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp chdir=/root/nginx-1.8.0
    - name: Compile nginx step 2
      command: make chdir=/root/nginx-1.8.0
    - name: Install nginx
      command: make install chdir=/root/nginx-1.8.0
    - name: Create cache directory
      file: path=/var/cache/nginx state=directory owner=nginx group=nginx mode=700
    - name: Copy nginx configuration file
      copy: src=../config_files/nginx.conf dest=/etc/nginx/nginx.conf
    - name: Copy modsecurity configuration file
      copy: src=../config_files/mod_security.conf dest=/etc/nginx/mod_security.conf
    - name: Copy nginx sysconfig file
      copy: src=../config_files/sysconfig-nginx dest=/etc/sysconfig/nginx
    - name: Copy nginx init script
      copy: src=../config_files/init-nginx dest=/etc/init.d/nginx mode=0755
    - name: Add nginx service
      command: /sbin/chkconfig --add nginx
    - name: Clone modsecurity OWASP core rules repository
      git: repo=https://github.com/SpiderLabs/owasp-modsecurity-crs.git dest=/tmp/owasp-modsecurity-crs update=no
    - name: Configure OWASP core rules (configuration file)
      shell: /bin/cat /tmp/owasp-modsecurity-crs/modsecurity_crs_10_setup.conf.example >> /etc/nginx/mod_security.conf
    - name: Configure OWASP core rules (base rules)
      shell: /bin/cat /tmp/owasp-modsecurity-crs/base_rules/*.conf >> /etc/nginx/mod_security.conf
    - name: Configure OWASP core rules (data files)
      shell: /bin/cp /tmp/owasp-modsecurity-crs/base_rules/*.data /etc/nginx/
